# Site Configuration
title: "keşif"
description: "Türkçe açıklamalı açık kaynak projeler"
url: "https://arifsolmaz.github.io"
baseurl: "/depo"

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - requirements.txt
  - "*.py"
  - queue.txt
  - history.txt
